name: 'Release changelog'
description: 'Update unreleased changelog section with current date and version'
author: 'superface.ai'
inputs:
  path-to-changelog:
    description: 'Path to changelog file in keep-a-changelog format'
    required: true
    default: ./CHANGELOG.md
  version:
    description: 'Version to be released'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
